{% set name = "WrightTools" %}
{% set version = "3.1.0" %}
{% set sha256 = "fc3557dd807a956d1d53be703015d459dc9d0e9305becc7a6776577cdcec7578" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - setuptools
    - pytest-runner
  run:
    - python
    - h5py >=2.7.0
    - imageio
    - matplotlib 2.*
    - numexpr
    - numpy
    - python-dateutil
    - pytz
    - scipy
    - tidy_headers

test:
  imports:
    - WrightTools

about:
  home: http://wright.tools/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Tools for loading, processing, and plotting multidimensional spectroscopy data.

extra:
  recipe-maintainers:
    - untzag
    - ksunden
