{% set name = "WrightTools" %}
{% set version = "3.2.5" %}
{% set sha256 = "3ff8be48826ee54105619920fa2c7fdd997a089d833f16321cfaedc8f1e67775" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - wt-tree = WrightTools.__main__:wt_tree

requirements:
  build:
    - python >=3.5
    - pip
    - setuptools
    - pytest-runner
  run:
    - python >=3.6
    - h5py >=2.7.0
    - imageio
    - matplotlib-base >=3.0
    - numexpr
    - numpy >=1.15.0
    - python-dateutil
    - scipy
    - tidy_headers >=0.3.0

test:
  imports:
    - WrightTools

about:
  home: http://wright.tools/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Tools for loading, processing, and plotting multidimensional spectroscopy data.

extra:
  recipe-maintainers:
    - untzag
    - ksunden
