{% set name = "WrightTools" %}
{% set version = "3.1.1" %}
{% set sha256 = "cbb6678b9dadafbd2c7c5e85186d490d7421c3aa26bae6954516bfde8eeef405" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - wt-tree = WrightTools.__main__:wt_tree

requirements:
  build:
    - python
    - pip
    - setuptools
    - pytest-runner
  run:
    - python
    - h5py >=2.7.0
    - imageio
    - matplotlib >=2.2
    - numexpr
    - numpy
    - python-dateutil
    - pytz
    - scikit-image
    - scipy
    - tidy_headers

test:
  imports:
    - WrightTools

about:
  home: http://wright.tools/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Tools for loading, processing, and plotting multidimensional spectroscopy data.

extra:
  recipe-maintainers:
    - untzag
    - ksunden
