{% set name = "WrightTools" %}
{% set version = "3.3.3" %}
{% set sha256 = "6d96d1c5f39b7d4ed2c57256c1408a74e843793853668c92637569435b2c388e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - wt-tree = WrightTools.__main__:wt_tree

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools
    - pytest-runner
  run:
    - python >=3.6
    - h5py >=2.7.0
    - imageio
    - matplotlib-base >=3.3
    - numexpr
    - numpy >=1.15.0
    - python-dateutil
    - scipy
    - tidy_headers >=0.3.0

test:
  imports:
    - WrightTools

about:
  home: http://wright.tools/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Tools for loading, processing, and plotting multidimensional spectroscopy data.

extra:
  recipe-maintainers:
    - untzag
    - ksunden
    - kameyer226
    - ddkohler
    - darienmorrow
