{% set name = "WrightTools" %}
{% set version = "3.1.4" %}
{% set sha256 = "af616c5c14ebc75d1413e75de25b124694da1ecd0e0f21037c1d531e41c7e292" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - wt-tree = WrightTools.__main__:wt_tree

requirements:
  build:
    - python >=3.5
    - pip
    - setuptools
    - pytest-runner
  run:
    - python >=3.5
    - h5py >=2.7.0
    - imageio
    - matplotlib >=2.2
    - numexpr
    - numpy >=1.15.0
    - python-dateutil
    - pytz
    - scikit-image
    - scipy
    - tidy_headers >=0.3.0

test:
  imports:
    - WrightTools

about:
  home: http://wright.tools/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Tools for loading, processing, and plotting multidimensional spectroscopy data.

extra:
  recipe-maintainers:
    - untzag
    - ksunden
