{% set name = "WrightTools" %}
{% set version = "3.5.3" %}
{% set sha256 = "8f2da35cd8c8b505fcbbb9ea6fcc9a3405b86e8b8ae66254a7ace3a7af6a82e2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/34/6e/e99283a8175e5cbf92a967946aa882794c51a094131814615d99ba34cfd7/wrighttools-3.5.3.tar.gz
  sha256: {{ sha256 }}

build:
  entry_points:
    - wt5=WrightTools.cli._wt5:cli
    - wt-convert=WrightTools.cli._units:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - h5py
    - imageio >=2.28.0
    - matplotlib-base >=3.4.0
    - numexpr
    - numpy >=1.15.0,<2.0
    - pint
    - python-dateutil
    - scipy
    - click
    - tidy_headers >=1.0.0
    - rich

test:
  imports:
    - WrightTools
  commands:
    - pip check
    - wt5 --help
    - wt-convert --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://wright.tools/
  license: MIT
  license_file: LICENSE.txt
  summary: Tools for loading, processing, and plotting multidimensional spectroscopy data.

extra:
  recipe-maintainers:
    - untzag
    - ksunden
    - kameyer226
    - ddkohler
    - darienmorrow
