{% set name = "WrightTools" %}
{% set version = "3.0.3" %}
{% set sha256 = "710a7bcf3ef59d839b15e8ce62ae83c6001667a049c071b43322d1896a691471" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
 
requirements:
  build:
    - python
    - pip
    - setuptools
    - pytest-runner
  run:
    - python
    - h5py >=2.7.0
    - imageio
    - matplotlib 2.*
    - numexpr
    - numpy
    - python-dateutil
    - pytz
    - scipy
    - pytest-runner
    - tidy_headers

test:
  imports:
    - WrightTools

about:
  home: http://wright.tools/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Tools for loading, processing, and plotting multidimensional spectroscopy data.

extra:
  recipe-maintainers:
    - untzag
    - ksunden
